abstract class StringConstants {
  static const String appTitle = "Todos app";
  static const String myTodos = "Мои задачи";
  static const String todosFromMe = "Задачи от меня";
  static const String task = "Задача";
  static const String taskDescription = "Описание";
  static const String enterDescription = "Введите описание";
  static const String executionDate = "Дата исполнения";
  static const String selectExecutor = "Выберите исполнителя";
  static const String executor = "Исполнитель";
  static const String selectPriority = "Выберите приоритет";
  static const String priority = "Приоритет";
  static const String createTask = "Создать задачу";
  static const String taskHasBeenCreated = "Задача создана";
  static const String ok = "ОК";
  static const String requiredField = "Обязательное поле";
  static const String minimumFiveCharacters = "Минимум 5 символов";
  static const String createTodo = "Create todo";
  static const String allPriorities = "Все приоритеты";
  static const String allStatuses = "Все статусы";
  static const String cancel = "Отмена";
  static const String changeStatus = "Смена статуса";
  static const String takeOnTheTask = "Взять задачу в работу?";
  static const String completeTheTask = "Завершить задачу?";
  static const String status = "Статус";
  static const String statusHasBeenChanged = "Статус изменен";
  static const String takeOn = "Взять в работу";
  static const String complete = "Завершить";
}
